FROM alpine:3.5

RUN apk add --no-cache ca-certificates openssl git hugo tar

ENV SERVANT_RELEASE=v0.1.1

COPY ./app app/

ADD build/servant /usr/local/bin/servant
RUN chmod +x /usr/local/bin/servant

WORKDIR /app

CMD "servant"